FROM harbor.sedp.co.kr/docker/node:18-alpine as build-stage
ARG profile=build_pub_dev
WORKDIR /app
COPY package*.json ./
COPY package-lock*.json ./
# COPY ["package.json", "package-lock.json*"] ./
RUN npm config set "strict-ssl" false -g
ENV GENERATE_SOURCEMAP=false
ENV NODE_OPTIONS=--max-old-space-size=16384
# RUN apk add --update python3 make g++
RUN npm cache clean --force
RUN npm --registry http://172.16.65.1:8080/repository/npm-group/ install --legacy-peer-deps
# RUN npm install --legacy-peer-deps
COPY . .
RUN npx kendo-ui-license activate
RUN npm run $profile
ENV HOST 0.0.0.0
EXPOSE 3000
ENTRYPOINT ["node", ".output/server/index.mjs"]
